Require sidekiq/api
Not sure which specific version of Sidekiq changed this. In sidekiq 4 and 5 the following occurs during boot:

```
NameError: uninitialized constant Sidekiq::ScheduledSet
.../gems/sidekiq_schedulable-0.1.1/lib/sidekiq_schedulable.rb:23:in `block in boot!'
```